spkkaryawan/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'spkkaryawan.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', 'spk.views.login'),
                       url(r'^logout/$', 'spk.views.logout', name='keluar'),
                       url(r'^401/$', 'spk.views.halaman_terlarang'),
                       url(r'^main/$', 'spk.views.main_page', name='menu-main'),
                       url(r'^unit/$', 'spk.views.menu_unit_kerja', name='menu-unit-kerja'),
                       url(r'^unit/sunting/(\d+)/$', 'spk.views.menu_unit_kerja_sunting', name='perbarui-unit-kerja'),
                       url(r'^unit/tambah/', 'spk.views.menu_unit_kerja_tambah', name='tambah-unit-kerja'),
                       url(r'^unit/hapus/(\d+)/$', 'spk.views.menu_unit_kerja_hapus', name='hapus-unit-kerja'),
                       url(r'^karyawan/$', 'spk.views.menu_karyawan', name='menu-karyawan'),
                       url(r'^karyawan/tambah/', 'spk.views.menu_karyawan_tambah', name='tambah-karyawan'),
                       url(r'^karyawan/sunting/(\d+)/$', 'spk.views.menu_karyawan_sunting', name='perbarui-karyawan'),
                       url(r'^karyawan/hapus/(\d+)/$', 'spk.views.menu_karyawan_hapus', name='hapus-karyawan'),
                       url(r'^kriteria/$', 'spk.views.menu_kriteria', name='menu-kriteria'),
                       url(r'^kriteria/sunting/(\d+)/$', 'spk.views.menu_kriteria_sunting', name='perbarui-kriteria'),
                       url(r'^pembobotan/$', 'spk.views.menu_pembobotan_ahp', name='menu-pembobotan'),
                       url(r'^pembobotan/hapus/$', 'spk.views.menu_hapus_pembobotan_ahp', name='hapus-bobot'),
                       url(r'^perangkingan/$', 'spk.views.menu_perangkingan_promete', name='menu-perangkingan'),
                       url(r'^perangkingan/unit/(\d+)/$', 'spk.views.json_unit_kerja'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spk/models.py
from django.db import models


class Pengguna(models.Model):
    LEVEL_CHOICES = (
        ('Admin', 'Admin'),
        ('K3', 'K3'),
        ('Personalia', 'Personalia'),
    )
    user_nama = models.CharField(max_length=80, verbose_name='Nama Pengguna')
    user_username = models.CharField(max_length=16, verbose_name='Username')
    user_password = models.CharField(max_length=20, verbose_name='Password')
    user_level = models.CharField(max_length=50, verbose_name='Level', choices=LEVEL_CHOICES)

    def __unicode__(self):
        return self.user_nama


class UnitKerja(models.Model):
    nama_unit_kerja = models.CharField(max_length=40)

    def __unicode__(self):
        return self.nama_unit_kerja


class Karyawan(models.Model):
    JENIS_KELAMIN = (
        ('Laki-laki', 'Laki-laki'),
        ('Perempuan', 'Perempuan'),
    )
    nik = models.CharField(max_length=10, primary_key=True)
    nama = models.CharField(max_length=80)
    jenis_kelamin = models.CharField(max_length=15, choices=JENIS_KELAMIN)
    tanggal_masuk = models.DateField()
    unit_kerja = models.ForeignKey(UnitKerja)
    foto = models.ImageField(upload_to='uploads/%Y/%m/%d')

    def __unicode__(self):
        return self.nik


class Laporan(models.Model):
    nilai_netflow = models.FloatField()
    ranking = models.IntegerField()
    karyawan = models.ForeignKey(Karyawan)

    def __unicode__(self):
        return self.karyawan.nik


class Kriteria(models.Model):
    TIPE_PREFERENSI = (
        ('I', 'I - Biasa'),
        ('II', 'II - Quasi'),
        ('III', 'III - Linier'),
    )
    MAX_MIN = (
        ('max', 'Maximum'),
        ('min', 'Minimum'),
    )
    nama_kriteria = models.CharField(max_length=40)
    tipe_preferensi = models.CharField(max_length=5, choices=TIPE_PREFERENSI)
    max_min = models.CharField(max_length=10, choices=MAX_MIN)
    parameter_p = models.IntegerField()
    parameter_q = models.IntegerField()
    nilai_karyawan = models.ManyToManyField(Karyawan, through='NilaiKaryawan')

    def __unicode__(self):
        return self.nama_kriteria


class BobotKriteria(models.Model):
    bobot = models.FloatField()
    kriteria = models.ForeignKey(Kriteria)

    def __unicode__(self):
        return self.kriteria.nama_kriteria


class NilaiKaryawan(models.Model):
    nilai = models.IntegerField()
    karyawan = models.ForeignKey(Karyawan)
    kriteria = models.ForeignKey(Kriteria)

    def __unicode__(self):
        return self.karyawan.nama

spk/forms.py
from django.forms import ModelForm, TextInput
from django.forms.widgets import Select

from spk.models import *


class UnitKerjaForm(ModelForm):
    class Meta:
        model = UnitKerja
        fields = ['nama_unit_kerja']
        widgets = {
            'nama_unit_kerja': TextInput(attrs={
                'Placeholder': 'Nama unit kerja',
                'style': 'height:40px;',
                'class': 'span6 disabled'
            })
        }


class KaryawanForm(ModelForm):
    class Meta:
        model = Karyawan
        fields = '__all__'
        widgets = {
            'nik': TextInput(attrs={
                'Placeholder': 'NIK Karyawan',
                'style': 'height:40px;',
                'class': 'span6 disabled',
                'readonly': 'true'
            }),
            'nama': TextInput(attrs={
                'Placeholder': 'Nama Karyawan',
                'style': 'height:40px;',
                'class': 'span6 disabled'
            }),
            'tanggal_masuk': TextInput(attrs={
                'Placeholder': 'Tanggal Masuk',
                'style': 'height:40px;',
                'class': 'span6 disabled'
            }),
            'jenis_kelamin': Select(attrs={
                'style': 'height:40px;',
                'class': 'span6 disabled'
            }),
            'unit_kerja': Select(attrs={
                'style': 'height:40px;',
                'class': 'span6 disabled'
            }),
        }


class KriteriaForm(ModelForm):
    class Meta:
        model = Kriteria
        exclude = ['id', 'nilai_karyawan']
        widgets = {
            'nama_kriteria': TextInput(attrs={
                'style': 'height:40px;',
                'Placeholder': 'Nama Kriteria',
                'class': 'span6 disabled',
                'readonly': 'true'
            }),
            'tipe_preferensi': Select(attrs={
                'style': 'height:40px;',
                'class': 'span6 disabled'
            }),
            'max_min': Select(attrs={
                'style': 'height:40px;',
                'class': 'span6 disabled'
            }),
            'parameter_p': TextInput(attrs={
                'style': 'height:40px;',
                'Placeholder': 'Nilai Parameter P',
                'class': 'span6 disabled'
            }),
            'parameter_q': TextInput(attrs={
                'style': 'height:40px;',
                'Placeholder': 'Nilai Parameter Q',
                'class': 'span6 disabled'
            }),
        }

spk/views.py
import json

from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import promethee as promet

from spk.forms import *


def login(request):
    if request.method == 'POST':
        if 'username' in request.POST and 'password' in request.POST:
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('spk.views.main_page'))
            else:
                messages.add_message(request, messages.ERROR, "Kombinasi username & password tidak tepat.")
                return HttpResponseRedirect(reverse('spk.views.login'))

    # redirect ke main page kalo user telah login
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('spk.views.main_page'))
    return render(request, 'login-page.html')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('spk.views.login'))


def halaman_terlarang(request):
    return render(request, 'terlarang.html')


@login_required(login_url='/401')
def main_page(request):
    return render(request, 'main.html', {'pengguna': request.user.username})


@login_required(login_url='/401')
def menu_pembobotan_ahp(request):
    if request.method == 'POST':
        '''
        batch insert bobot pengetahuan mesin
        '''
        BobotKriteria.objects.bulk_create([
            BobotKriteria(bobot=request.POST.get('bobot_pengetahuan_mesin'), kriteria=Kriteria.objects.get(id=2)),
            BobotKriteria(bobot=request.POST.get('bobot_kondisi_psikis'), kriteria=Kriteria.objects.get(id=3)),
            BobotKriteria(bobot=request.POST.get('bobot_kondisi_mesin'), kriteria=Kriteria.objects.get(id=4)),
            BobotKriteria(bobot=request.POST.get('bobot_kondisi_lingkungan'), kriteria=Kriteria.objects.get(id=5)),
            BobotKriteria(bobot=request.POST.get('bobot_kondisi_fisik'), kriteria=Kriteria.objects.get(id=6)),
            BobotKriteria(bobot=request.POST.get('bobot_masa_kerja'), kriteria=Kriteria.objects.get(id=7)),
            BobotKriteria(bobot=request.POST.get('bobot_pendidikan'), kriteria=Kriteria.objects.get(id=8)),
            BobotKriteria(bobot=request.POST.get('bobot_usia'), kriteria=Kriteria.objects.get(id=9))
        ])

        messages.add_message(request, messages.SUCCESS, "Pembobotan kriteria berhasil.")
        return HttpResponseRedirect(reverse('spk.views.menu_pembobotan_ahp'))

    # cek apakah data bobot sudah ada isinya atau belum
    available = BobotKriteria.objects.all().exists()
    bobot = BobotKriteria.objects.values_list('bobot', flat=True)
    return render(request, 'menu-bobot-ahp.html',
                  {'dropdown_value': [x for x in range(0, 10)], 'hit': available, 'bobot': bobot})


@login_required(login_url='/401')
def menu_hapus_pembobotan_ahp(request):
    BobotKriteria.objects.all().delete()
    messages.add_message(request, messages.SUCCESS, "Bobot kriteria berhasil dihapus.")
    return HttpResponseRedirect(reverse('spk.views.menu_pembobotan_ahp'))


@login_required(login_url='/401')
def menu_kriteria(request):
    return render(request, 'menu-kriteria.html', {'kriteria': Kriteria.objects.all()})


@login_required(login_url='/401')
def menu_kriteria_sunting(request, id_kriteria):
    kriteria = Kriteria.objects.get(pk=id_kriteria)
    if request.method == 'POST':
        form = KriteriaForm(request.POST, instance=kriteria)
        if form.is_valid():
            kriteria.nama_kriteria = form.cleaned_data['nama_kriteria']
            kriteria.parameter_p = form.cleaned_data['parameter_p']
            kriteria.parameter_q = form.cleaned_data['parameter_q']
            kriteria.tipe_preferensi = form.cleaned_data['tipe_preferensi']
            kriteria.max_min = form.cleaned_data['max_min']
            kriteria.save()
            messages.add_message(request, messages.SUCCESS, 'Kriteria %s berhasil diperbarui.' % kriteria.nama_kriteria)
            return HttpResponseRedirect(reverse('spk.views.menu_kriteria'))
        else:
            return render(request, 'menu-kriteria-form.html', {'form': form})
    form = KriteriaForm(instance=kriteria)
    return render(request, 'menu-kriteria-form.html', {'form': form})


@login_required(login_url='/401')
def menu_karyawan(request):
    karyawan_list = Karyawan.objects.all()
    paginator = Paginator(karyawan_list, 5)  # display 5 karyawan per page

    page = request.GET.get('page')
    try:
        karyawans = paginator.page(page)
    except PageNotAnInteger:
        karyawans = paginator.page(1)
    except EmptyPage:
        karyawans = paginator.page(paginator.num_pages)
    return render(request, 'menu-karyawan.html', {'karyawan': karyawans})


@login_required(login_url='/401')
def menu_karyawan_tambah(request):
    if request.method == 'POST':
        form = KaryawanForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Karyawan berhasil ditambahkan.')
            return HttpResponseRedirect(reverse('spk.views.menu_karyawan'))
        else:
            return render(request, 'menu-karyawan-form.html', {'form': form, 'button': 'Tambahkan'})

    # ambil data nik terakhir
    last_nik = Karyawan.objects.values_list('nik', flat=True).last()

    # generate_nik = '1000000001' kalo data kosong, dan tambah 1 last_nik yang sudah dikonversi ke int
    generate_nik = 1000000001 if last_nik is None else int(last_nik) + 1

    form = KaryawanForm(initial={'nik': generate_nik})
    return render(request, 'menu-karyawan-form.html', {'form': form, 'button': 'Tambahkan'})


@login_required(login_url='/401')
def menu_karyawan_sunting(request, nik):
    karyawan = Karyawan.objects.get(nik=nik)
    if request.method == 'POST':
        form = KaryawanForm(request.POST, request.FILES, instance=karyawan)
        if form.is_valid():
            karyawan.nama = form.cleaned_data['nama']
            karyawan.jenis_kelamin = form.cleaned_data['jenis_kelamin']
            karyawan.tanggal_masuk = form.cleaned_data['tanggal_masuk']
            karyawan.unit_kerja = form.cleaned_data['unit_kerja']
            karyawan.save()
            messages.add_message(request, messages.SUCCESS, 'Data %s berhasil diperbarui.' % karyawan.nama)
            return HttpResponseRedirect(reverse('spk.views.menu_karyawan'))
        else:
            print form.cleaned_data['unit_kerja']
            print form.errors
            return render(request, 'menu-karyawan-form.html', {'form': form.errors, 'button': 'Perbarui'})
    form = KaryawanForm(instance=karyawan)
    return render(request, 'menu-karyawan-form.html', {'form': form, 'button': 'Perbarui'})


@login_required(login_url='/401')
def menu_karyawan_hapus(request, nik):
    Karyawan.objects.filter(nik__exact=nik).delete()
    messages.add_message(request, messages.SUCCESS, 'Data %s berhasil dihapus.' % nik)
    return HttpResponseRedirect(reverse('spk.views.menu_karyawan'))


@login_required(login_url='/401')
def menu_unit_kerja(request):
    return render(request, 'menu-unit-kerja.html', {'uker': UnitKerja.objects.all()})


@login_required(login_url='/401')
def menu_unit_kerja_tambah(request):
    if request.method == 'POST':
        form = UnitKerjaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Data berhasil ditambahkan.")
            return HttpResponseRedirect(reverse('spk.views.menu_unit_kerja'))
        else:
            return render(request, 'menu-unit-kerja-form.html', {'form': form, 'button': 'Tambahkan'})
    form = UnitKerjaForm()
    return render(request, 'menu-unit-kerja-form.html', {'form': form, 'button': 'Tambahkan'})


@login_required(login_url='/401')
def menu_unit_kerja_hapus(request, id_unit):
    unitkerja = UnitKerja.objects.get(id=id_unit)
    unitkerja.delete()
    messages.add_message(request, messages.SUCCESS, "Data %s berhasil dihapus." % unitkerja.nama_unit_kerja)
    return HttpResponseRedirect(reverse('spk.views.menu_unit_kerja'))


@login_required(login_url='/401')
def menu_unit_kerja_sunting(request, id_unit):
    data_sunting = UnitKerja.objects.get(pk=id_unit)
    if request.method == 'POST':
        form = UnitKerjaForm(request.POST, instance=data_sunting)
        if form.is_valid():
            data_sunting.nama_unit_kerja = form.cleaned_data['nama_unit_kerja']
            data_sunting.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Data %s berhasil diperbarui." % data_sunting.nama_unit_kerja)
            return HttpResponseRedirect(reverse('spk.views.menu_unit_kerja'))
        else:
            return render(request, 'menu-unit-kerja-form.html', {'form': form, 'button': 'Perbarui'})
    form = UnitKerjaForm(instance=data_sunting)
    return render(request, 'menu-unit-kerja-form.html', {'form': form, 'button': 'Perbarui'})


@login_required(login_url='/401')
def json_unit_kerja(request, id_unit):
    unit_kerja = Karyawan.objects.filter(unit_kerja__exact=UnitKerja.objects.get(pk=id_unit)).values_list('nama',
                                                                                                          flat=True)
    return HttpResponse(json.dumps([unicode(i) for i in unit_kerja]), content_type="application/json")


@login_required(login_url='/401')
def menu_perangkingan_promete(request):
    if request.method == 'POST':
        pengetahuan_mesin = [int(i) for i in request.POST.getlist('pengetahuan_mesin')]

spk/templates/base-login.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %} <!-- ini bagian judul --> {% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	    <meta name="apple-mobile-web-app-capable" content="yes"> 

        {% block extracss %} <!-- ini bagian kalo ada tambahan css --> {% endblock %}

		<!-- css files -->
		<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />

		<link href="{{ STATIC_URL }}css/font-awesome.css" rel="stylesheet">
		<link href="{{ STATIC_URL }}css/font-google.css" rel="stylesheet">
		    
		<link href="{{ STATIC_URL }}css/style.css" rel="stylesheet" type="text/css">
		<link href="{{ STATIC_URL }}css/pages/signin.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
			    	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			    		<span class="icon-bar"></span>
			    		<span class="icon-bar"></span>
			    		<span class="icon-bar"></span>
			    	</a>

			    	<a class="brand" href="#">Sistem Pendukung Keputusan Pemilihan Karyawan untuk Penerapan Program Kesehatan dan Keselamatan Kerja
			    	</a>
				        
			       <img src="{{ STATIC_URL }}img/logo.jpg" style="height:40px;">
			   </div>
			</div>
		</div>

		<div id="content">
			{% block content %} <!-- ini bagian konten isi web --> {% endblock %}
		</div>

		<!-- javascript files -->
		<script src="{{ STATIC_URL }}js/jquery-1.7.2.min.js"></script>
		<script src="{{ STATIC_URL }}js/bootstrap.js"></script>
		<script src="{{ STATIC_URL }}js/signin.js"></script>
        {% block extrajs %} <!-- ini bagian kalo ada tambahan js --> {% endblock %}
	</body>
</html>

spk/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %} <!-- ini bagian judul --> {% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	    <meta name="apple-mobile-web-app-capable" content="yes"> 

        {% block extracss %} <!-- ini bagian kalo ada tambahan css --> {% endblock %}

		<!-- css files -->
		<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />

		<link href="{{ STATIC_URL }}css/font-awesome.css" rel="stylesheet">
		<link href="{{ STATIC_URL }}css/font-google.css" rel="stylesheet">
		    
		<link href="{{ STATIC_URL }}css/style.css" rel="stylesheet" type="text/css">
		<link href="{{ STATIC_URL }}css/pages/signin.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
			    	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			    		<span class="icon-bar"></span>
			    		<span class="icon-bar"></span>
			    		<span class="icon-bar"></span>
			    	</a>

			    	<a class="brand" href="#">Sistem Pendukung Keputusan Pemilihan Karyawan untuk Penerapan Program Kesehatan dan Keselamatan Kerja
			    	</a>
				        
			       <img src="{{ STATIC_URL }}img/logo.jpg" style="height:40px;">
			   </div>
			</div>
		</div>

		<div class="subnavbar">
            <div class="subnavbar-inner">
                <div class="container">
                    <ul class="mainnav">
                        <li class="active"><a href="{% url 'menu-main' %}"><i class="icon-dashboard"></i><span>Home</span> </a> </li>
                        <li class="active"><a href="{% url 'menu-karyawan' %}"><i class="icon-eye-open"></i><span>Karyawan</span> </a> </li>
                        <li class="active"><a href="{% url 'menu-unit-kerja' %}"><i class="icon-facetime-video"></i><span>Unit Kerja</span> </a> </li>
                        <li class="active"><a href="{% url 'menu-kriteria' %}"><i class="icon-folder-open"></i><span>Kriteria</span> </a> </li>
                        <li class="active"><a href="{% url 'menu-pembobotan' %}"><i class="icon-fire"></i><span>Pembobotan</span> </a> </li>
                        <li class="active"><a href="{% url 'menu-perangkingan' %}"><i class="icon-bar-chart"></i><span>Perangkingan</span> </a> </li>
                        <li class="active"><a href="#"><i class="icon-list-alt"></i><span>Laporan</span> </a> </li>
                        <li class="dropdown active">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-long-arrow-down"></i><span >Akun</span> <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'keluar' %}">Keluar</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

		<div id="content">
			{% block content %} <!-- ini bagian konten isi web --> {% endblock %}
		</div>

		<!-- javascript files -->
		<script src="{{ STATIC_URL }}js/jquery-1.7.2.min.js"></script>
		<script src="{{ STATIC_URL }}js/bootstrap.js"></script>
		<script src="{{ STATIC_URL }}js/signin.js"></script>
        {% block extrajs %} <!-- ini bagian kalo ada tambahan js --> {% endblock %}
	</body>
</html>

spk/templates/main.html
{% extends "base.html" %}
{% block title %} SPK | Halaman Utama {% endblock %}

{% block content %}
<div class="main-inner">
    <div class="container">
        <div class="row">
            <div class="span12">
                <h1>Selamat Datang, {{ pengguna }}</h1>
            </div><!-- /widget -->
        </div>
    </div>
</div>
{% endblock %}

spk/templates/menu-karyawan-form.html
{% extends "base.html" %}
{% block title %} SPK | Karyawan {% endblock %}

{% block extracss %}
    <link href="{{ STATIC_URL }}jqueryui/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <link href="{{ STATIC_URL }}jqueryui/jquery-ui.structure.min.css" rel="stylesheet" type="text/css" />
    <link href="{{ STATIC_URL }}jqueryui/jquery-ui.theme.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<div class="main-inner" style="margin-top:3%;">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget">
                    <div class="widget-header">
                        <i class="icon-user"></i>
                        <h3>Tambah Karyawan</h3>
                    </div> <!-- /widget-header -->

                    <div class="widget-content">
                        <div id="ubah">
                            <form id="edit-profile" class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset>
                                    <div class="control-group">
                                        <!--<label class="control-label">Nama Unit Kerja</label>-->
                                        <span>{{ kesalahan }}</span>
                                        <div class="controls">
                                            {{ form.as_p }}
                                        </div> <!-- /controls -->
                                    </div> <!-- /control-group -->

                                    <div class="control-group">
                                        <div class="controls">
                                            <input type="submit" value="{{ button }}" class="btn btn-info">
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div><!--end idubah-->
                    </div><!--widget-content-->
                </div><!-- /widget -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
    <script src="{{ STATIC_URL }}jqueryui/external/jquery/jquery.js"></script>
    <script src="{{ STATIC_URL }}jqueryui/jquery-ui.min.js"></script>
    <script src="{{ STATIC_URL }}jqueryui/jquery.ui.datepicker.validation.min.js"></script>
    <script>
        $("#id_tanggal_masuk").datepicker({
            dateFormat:'yy-mm-dd',
            maxDate:0,
            showAnim:'slideDown',
            changeMonth:'true',
            changeYear:'true'
        });
    </script>
{% endblock %}

spk/templates/menu-kriteria-form.html
{% extends "base.html" %}
{% block title %} SPK | Kriteria {% endblock %}

{% block content %}
<div class="main-inner" style="margin-top:3%;">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget">
                    <div class="widget-header">
                        <i class="icon-user"></i>

                        <h3>Perbarui Kriteria</h3>
                    </div>
                    <!-- /widget-header -->

                    <div class="widget-content">
                        <div id="ubah">
                            <form id="edit-profile" class="form-horizontal" action="" method="POST">
                                {% csrf_token %}
                                <fieldset>
                                    <div class="control-group">
                                        <div class="controls">
                                            {{ form.as_p }}
                                        </div>
                                        <!-- /controls -->
                                    </div>
                                    <!-- /control-group -->

                                    <div class="control-group">
                                        <div class="controls">
                                            <input type="submit" value="Perbarui" class="btn btn-info">
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                        <!--end idubah-->
                    </div>
                    <!--widget-content-->
                </div>
                <!-- /widget -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
    $(document).ready(function(){
        $("#id_tipe_preferensi").change(function() {
            var nilai = this.value;
            console.log(nilai);
            if (nilai === 'I') {
                $("#id_parameter_p").val(0).attr("readonly", true);
                $("#id_parameter_q").val(0).attr("readonly", true);
            } else if (nilai === 'II') {
                $("#id_parameter_p").val(0).attr("readonly", true);
                $("#id_parameter_q").val("");
            } else if (nilai === 'III') {
                $("#id_parameter_p").val("");
                $("#id_parameter_q").val(0).attr("readonly", true);
            } else {
                $("#id_parameter_p").val("").attr("readonly", true);
                $("#id_parameter_q").val("").attr("readonly", true);
            }
        });
    });
</script>
{% endblock %}